name: Configure new release branch

on:
  create

jobs:
  reset_version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: git config --global user.email "robby@atweel.com"
    - run: git config --global user.name "Robby the robot"
    - run: yarn config set version-git-message "Reset version according to branch (%s)"
    - run: yarn version --new-version ${GITHUB_REF#refs/heads/releases\/v}.0 --no-commit-hooks
    - run: git fetch
    - run: git checkout master
    - run: git pull
    - run: git merge -X ours $GITHUB_REF
    - run: git push
