name: Configure new release branch

on:
  create

jobs:
  reset_version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: echo ${GITHUB_REF}
    - run: yarn version --new-version ${GITHUB_REF#refs/heads/releases\/v}.0 --no-commit-hooks